quant:
    a_qconfig:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 4
        symmetric: False
        ch_axis: -1
    w_qconfig:
        quantizer: AdaRoundFakeQuantize
        observer: MSEObserver
        bit: 4
        symmetric: True
        ch_axis: -1  # Tensor wise is -1
    calibrate: 1024
    recon:
        batch_size: 1
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.01
        iters: 20000
        b_range: [20, 2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        drop_prob: 0.5
# model:                    # architecture details
#     type: resnet18       # model name
#     kwargs:
#         num_classes: 1000
#     path: /mnt/lustre/weixiuying/model_zoo/resnet50_imagenet.pth.tar
# data:
#     path: /SSD/ILSVRC2012/
#     batch_size: 64
#     num_workers: 4
#     pin_memory: True
#     input_size: 224
#     test_resize: 256
process:
    seed: 1005